name: Test CI

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup
      run: ./setup.ps1
    - name: Build
      run: ./build.ps1 -NoPause
    - name: Test
      run: bin/test.exe
