name: Test CI

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  show_config:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Config
      run: ./config.ps1

  build_default:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup
      run: ./setup.ps1
    - name: Build
      run: ./build.ps1 -NoPause
    - name: Test
      run: |
        $env:Path = "C:\Windows\system32;$($env:Path)"
        bin/test.exe

  build_workaround:
    runs-on: windows-latest
    env:
      DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR: true
    steps:
    - uses: actions/checkout@master
    - name: Setup
      run: ./setup.ps1
    - name: Build
      run: ./build.ps1 -NoPause
    - name: Test
      run: |
        $env:Path = "C:\Windows\system32;$($env:Path)"
        bin/test.exe
